import { Router, type IRouter } from "express";
import healthRouter from "./health";
import { authRouter } from "./auth";
import { dashboardRouter } from "./dashboard";
import { entrancesRouter } from "./entrances";
import { intercomsRouter } from "./intercoms";
import { villasRouter } from "./villas";
import { reservationsRouter } from "./reservations";
import { vehiclesRouter } from "./vehicles";
import { accessRouter } from "./access";
import { camerasRouter } from "./cameras";
import { logsRouter } from "./logs";
import { snapshotsRouter } from "./snapshots";
import { eventsRouter } from "./events";
import { mockRouter } from "./mock";
import { settingsRouter } from "./settings";
import { diagnosticsRouter } from "./diagnostics";
import { exportRouter } from "./export";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/dashboard", dashboardRouter);
router.use("/entrances", entrancesRouter);
router.use("/intercoms", intercomsRouter);
router.use("/villas", villasRouter);
router.use("/reservations", reservationsRouter);
router.use("/vehicles", vehiclesRouter);
router.use("/access", accessRouter);
router.use("/cameras", camerasRouter);
router.use("/logs", logsRouter);
router.use("/snapshots", snapshotsRouter);
router.use("/events", eventsRouter);
router.use("/mock", mockRouter);
router.use("/settings", settingsRouter);
router.use("/diagnostics", diagnosticsRouter);
router.use("/export", exportRouter);

export default router;
